name: e2e-v2

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  e2eTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get latest API tag
        id: api_tag
        run: |
          TAG=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/users/jbustol271/packages/container/hangman-api-cep-grupo-a/versions \
            | jq -r '.[0].metadata.container.tags[0]')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Get latest FRONTEND tag
        id: front_tag
        run: |
          TAG=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/users/jbustol271/packages/container/hangman-frontend-cep-grupo-a/versions \
            | jq -r '.[0].metadata.container.tags[0]')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Run needed containers
        run: |
          echo "API TAG: ${{ steps.api_tag.outputs.tag }}"
          echo "FRONT TAG: ${{ steps.front_tag.outputs.tag }}"

          # API
          docker run -d -p 3001:3000 \
            ghcr.io/jbustol271/hangman-api-cep-grupo-a:${{ steps.api_tag.outputs.tag }}

          # FRONTEND
          docker run -d -p 8080:8080 \
            -e API_URL=http://localhost:3001 \
            ghcr.io/jbustol271/hangman-frontend-cep-grupo-a:${{ steps.front_tag.outputs.tag }}

      - name: Install dependencies
        run: npm ci
        working-directory: ./hangman-e2e/e2e

      - name: Execute e2e tests
        uses: cypress-io/github-action@v7
        with:
          working-directory: ./hangman-e2e/e2e
